name: octokit/graphql-action
on: workflow_dispatch
jobs:
  generateIssuesReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo    
      - uses: octokit/graphql-action@v2.x
        id: get_issues
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                issues(last:100, states:OPEN) {
                  edges {
                    node {
                        id 
                        title
                        url
                        number
                        state
                        author {
                          url
                        }
                        labels(first:5) {
                          edges {
                            node {
                              name
                            }
                          }
                        }
                      body
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "mkdir outputs"
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "outputs/issues.json"
          json: ${{ steps.get_issues.outputs.data }}
      - name: Render template
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: issues.j2
          output_file: outputs/issues.md
          data_file: outputs/issues.json
          data_format: json # Will try to guess from the extension instead (unnecessary in this case)               
      - name: Build PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: outputs
          output_dir: outputs           
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: outputs
          path: outputs          