name: octokit/graphql-action
on: workflow_dispatch
jobs:
  generateIssuesReport:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_issues
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                issues(last:100, states:OPEN) {
                  edges {
                    node {
                        id 
                        title
                        url
                        number
                        state
                        author {
                          url
                        }
                        labels(first:5) {
                          edges {
                            node {
                              name
                            }
                          }
                        }
                      body
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "outputs/issues.json"
          json: ${{ steps.get_issues.outputs.data }}
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: outputs
          path: outputs          